### ISSUE TITLE
update the blockchain helmcharts with the right ports configurations 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc-solutions-charts#10]
- [x] #7 dash
- [ ] #8 harmony
- [x] #6 digibyte
- [ ] #9 tomochain
- [ ] matic

**Comment by rkhamis** [comment]
@abdulgig thanks!

but could you just move to the verification swimlane? we don't use the verification label anymore

**Comment by sasha-astiadi** [comment]
add matic, moved back to in progress , because of ingress

**Comment by sasha-astiadi** [comment]
first 2 with ingress- digibyte and dash for marketplace 2.4 instead of 4.
Ready to test tomorrow
