### ISSUE TITLE
Owncloud deployment SSO on the TF NOW marketplace?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/vdc-solutions-charts#116]
Can we do a quick review of how difficult it is to add the install of owncloud on the TF Grid:

There is a pretty extensive description: https://owncloud.com/news/how-to-set-up-an-owncloud-in-3-minutes/

Is this feasible within a few days to have this deployed in the VDC ?  Have has two requests already with regards to be seeing this as a demo in the TF GRid -> since it is a docker image, this should not be too impactful.

https://owncloud.com/news/how-to-set-up-an-owncloud-in-3-minutes/

**Comment by sasha-astiadi** [comment]
its a contest tbd on monday for prioritization, we will see, how team feels on working on this for this sprint or next sprint @xmonader thabet feel free to decide

**Comment by xmonader** [comment]
moving to the next milestone. Already this milestone has too many unstable features.

**Comment by weynandkuijpers** [comment]
ok - fair enough.  I'll try to make this a "developer install" through Kubernetes deployment mechanism without needing internal development support.  For the next release (2.7) we'll plan to adopt and implement deeper integrations.

**Comment by ashraffouda** [comment]
if we allowed the users to directly login with tfconnect they can abuse the storage capacity 
so we will do the following
the default admin will have a username/password
other users will be allowed to login with tfconnect with quota 1MB
the admin can then increase there quotas and add them to group and manage access ....

**Comment by sameh-farouk** [comment]
After discussing, the flow above modified to this one.

User logged in for first time with tf-connect will have a disabled account. Admin then will have the option to enable new accounts from his dashboard on demand, and set the account quota as he desired.

**Comment by weynandkuijpers** [comment]
Okay - will do the trick :-)

**Comment by RafyAmgadBenjamin** [comment]
Done
### Branch
`development`

### PR
https://github.com/threefoldtech/vdc-solutions-charts/pull/130
https://github.com/threefoldtech/js-sdk/pull/2851
