### ISSUE TITLE
Matic - Validator Node And update status page

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/vdc-solutions-charts#120]
**For Validator Node,**

- [x] Update existing matic docker Images
- [x] Update existing matic helm chart to add validator settings (PR = https://github.com/threefoldtech/vdc-solutions-charts/pull/125)
- [x] Update existing chatflow (PR = https://github.com/threefoldtech/js-sdk/pull/2844 )
- [x] Update status pages that would serve for each node type 
- [x] Test and Roll out

- [x] @BenjellounO need to review with matic on this process

- [x] need to deploy it on separate vdc

- [x] need minimum platinum  package

- [x] @BenjellounO need to confirm to matic if we need platinum package or less is possible

Related story: https://github.com/threefoldtech/vdc-solutions-charts/issues/39

**Comment by sasha-astiadi** [comment]
"waiting for technical spec review / confirmation from matic side until, move to 2.7 @BenjellounO

**Comment by xmonader** [comment]
@abdulgig can you update the status here. if ready let's move to verification.

**Comment by abdulgig** [comment]
Already done
