### ISSUE TITLE
Deployment Matic node on new diamond VDC fails due to insufficient resources

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/vdc-solutions-charts#124]
I tried to deploy a Matic / Polygon node but it gives an error for reason 'insufficient compute/memory resources'. This can't be, it's a new diamond VDC. 

![image](https://user-images.githubusercontent.com/30384423/111622979-1d622380-87ea-11eb-9db8-2ebad01cef84.png)

VDC name: vdcdiamondtest

**Comment by abdulgig** [comment]
This issue should be closed with reference to explanation provided here https://github.com/threefoldtech/vdc-solutions-charts/issues/121

Therefore, moving it under verification

**Comment by gmachtel** [comment]
Works now.
