### ISSUE TITLE
VDC: helm charts for blockchain solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc-solutions-charts#13]
prepare helm charts for all of the blockchain solutions
- [x] all helm charts need to use a decent image
- [x] all images need to have a proper entrypoint script
- [x] all configurations need to be provided using configmaps / secrets
- [x] deployments needs to be done properly using the right images, right configs completely managed by kubernetes
- [x] all solutions need to use proper volumes
- [x] no manual connection / changing state using ssh or kubectl exec after the deployment

please follow this readme https://github.com/threefoldtech/vdc-solutions-charts/blob/master/README.md

notes: [etherum chart](https://github.com/helm/charts/blob/master/stable/ethereum/)  , [ibm hyperledger](https://github.com/IBM/blockchain-network-on-kubernetes/blob/master/README.md#4-deploy-hyperledger-fabric-network-into-kubernetes-cluster) 

deadline: end of w1 jan 2021

**Comment by xmonader** [comment]
@abdulgig now We got the ingress updated you can start working on updating your solutions

**Comment by abdulgig** [comment]
@xmonader thanks for updating, we ll check it out

**Comment by sasha-astiadi** [comment]
> With this, we will start with
> 
> * [x]  Digibyte Node
> * [x]  Dash Node
> * [x]  Harmony Node
> * [x]  Tomochain Node
> 
> Unlike other solutions which mostly have well cooked helm charts available online, for blockchain nodes this may not be the case.
> 
> We will use and modify existing templates to see how it goes

- [ ] matic node https://github.com/threefoldtech/tf_operations/issues/55

**Comment by sasha-astiadi** [comment]
first 2 with ingress-  digibyte and dash for marketplace 2.4 instead of 4.
Ready to test tomorrow

**Comment by abdulgig** [comment]
Just updating this one, for partners below,

- [x] Digibyte
- [ ] Dash

@BenjellounO, since we have https://github.com/threefoldtech/vdc-solutions-charts/issues/49, we will need to do the following,

  - [ ] Why do the users need any terminal access ? Please enlist everything possible so that we can automate
  - [ ] Clearly identity all inputs so that we can use the chatflows / charts
  - [ ] How do they currently monitor all their services so that we can alternately provide it via k8s itself or a status page for the node

**Comment by abdulgig** [comment]
For Digibyte, we have a PR here https://github.com/threefoldtech/vdc-solutions-charts/pull/62

We are still working with Dash folks

**Comment by sasha-astiadi** [comment]
this story is obsolete. we first focus on digibyte, and we create issue per helm chart, not all.| for 2.4; digibyte helm chart #66
