### ISSUE TITLE
publishingtools charts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc-solutions-charts#16]
- [x] wiki
- [x] blog
- [x] website

part of https://github.com/threefoldtech/vdc/issues/12

**Comment by abom** [comment]
Publishing tools chart were added, it should support publishing a single website/wiki or blog for now, docs can be found [here](https://github.com/threefoldtech/vdc-solutions-charts/blob/474fe88b006f47a8825fcdeb34a8a87e6876cf0e/charts/publishingtools/README.md).

Also created the base alpine image for publishing tools at https://github.com/threefoldtech/tf-images/pull/30.
