### ISSUE TITLE
Cryptpad chart mount volume to extend user storage

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/vdc-solutions-charts#18]
**Check how can we mount a volume on k8s** to extend user storage for cryptpad chart
current chart works with 50MB only (the default storage on cryptpad image)

**Comment by sasha-astiadi** [comment]
are we doing it? if yes, please label milestone now @xmonader

**Comment by AhmedHanafy725** [comment]
**Verified**
![image](https://user-images.githubusercontent.com/41957921/107229683-c9b02d80-6a26-11eb-9471-5ad64978bb39.png)
