### ISSUE TITLE
Update charts to use certificate resolver

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/vdc-solutions-charts#31]
In vdc deployment in js-sdk, traefik was upgraded from v1 to v2, and 3 custom certificate resolver were configured (le for letsencrypt, default for le staging, and ghanem for ca1.grid.tf).

So, these three lines should be added to use one of those resolvers in the ingress definitions in the annotations section.
```
    {{- if .Values.ingress.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.ingress.certresolver }}
    {{- end }}
```
A sample of this change can be found in mattermostonsteriods chart definition.

- [x] cryptpad
- [x] discourse
- [x] gitea
- [x] mattermost
- [x] peertube
- [x] taiga
- [x] zeroci

**Comment by AhmedSa-mir** [comment]
Charts updated: https://github.com/threefoldtech/vdc-solutions-charts/commit/90746aae86f0485d84aa05334dbd471257015add
