### ISSUE TITLE
TF NOW Marketplace - add filebrowser widget

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/vdc-solutions-charts#32]
**Title: Filebrowser**

**description:** 
Filebrowser is a file managing solution within a specified directory and it can be used to upload, delete, preview, rename and edit your files.

**action:**
**deploy** - not coming soon  since we have the flist / helm charts

icon (crop img only without the title)
![banner](https://user-images.githubusercontent.com/43240801/102103660-8de55700-3e2d-11eb-9223-2d13d80a4277.png)

**Label**
Decentralized Office

**Comment by ken-de-moor** [comment]
Old wrong issue it seems, tickets refering to it are talking about VDC, and this is about adding the tile not the actual thing. The tile can only be added if there's a working solution. Will close for now as it's a weird way of following up another thing entirely.
