### ISSUE TITLE
update ingress configuration for all charts 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/vdc-solutions-charts#36]
we now add for each charts that needs ssl certificate this section 
```
ingress:
  certresolver: default 
```
this thing will fail if you have subchart that needs to ingress config because it has no access to `values.ingress.certresolver`
and this happens for monitoring-stack chart because it has grafana as subchart
so let's modify this section to be under global
```
global:
  ingress:
    certresolver: default
```
so it will be easy to access it with `.values.global.ingress.certresolver` in any chart and it's subcharts

- [x] cryptpad
- [x] discourse
- [x] gitea
- [x] kubeapps
- [x] mattermost
- [x] monitoring-stack
- [x] peertube
- [x] publishingtools
- [x] taiga
- [x] zeroci

**Comment by sasha-astiadi** [comment]
@ashraffouda remove dash, tomo for now.
