### ISSUE TITLE
filebrowser doesn't upload files

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/vdc-solutions-charts#55]
- deploy document server
- deploy file browser
- try to upload file
![Screenshot from 2021-01-20 12-47-31](https://user-images.githubusercontent.com/10658229/105164389-bee83400-5b1d-11eb-8ef1-fd244841f901.png)

- try to create file
![Screenshot from 2021-01-20 12-48-54](https://user-images.githubusercontent.com/10658229/105164511-e3dca700-5b1d-11eb-88dd-496e2675e6e4.png)

empty page

**Comment by sasha-astiadi** [comment]
@ken-de-moor move filebrowser to 2.5 instead of 2.4
