### ISSUE TITLE
document server needs to be dependancy of file server

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/vdc-solutions-charts#56]
document server only shows that page
![Screenshot from 2021-01-20 12-34-41](https://user-images.githubusercontent.com/10658229/105164727-2605e880-5b1e-11eb-8a77-90c0d96265d5.png)

so it should run in background or as a dependency of the file browser, me as i user won't understand what it does through that empty page

**Comment by sasha-astiadi** [comment]
move to marketplace 2.5 / 3bot 2.5
