### ISSUE TITLE
digibyte expected to have port 12024 open

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc-solutions-charts#6]
Looking at https://github.com/threefoldfoundation/blockchain_partners/tree/master/Digibyte/helm and the files here https://github.com/threefoldfoundation/blockchain_partners/tree/master/Digibyte/helm I don't see anything related to 12024 at all?

https://www.dgbwiki.com/index.php?title=Running_a_full_node

**Comment by abdulgig** [comment]
Relevant ports were exposed and helm chart was updated !

**Comment by sasha-astiadi** [comment]
@BenjellounO please test and verify
