### ISSUE TITLE
Error deploying filebrowser

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/vdc-solutions-charts#64]
https://myth-hamdy.vdcdev.grid.tf/vdc_dashboard/#/solutions/filebrowser

Logs
```
https://vdcmonitor.grid.tf/explore?orgId=2&left=["now-30m","now","InfluxDB",{"datasource":"InfluxDB","groupBy":[],"measurement":"logs","orderByTime":"ASC","policy":"default","resultFormat":"logs","select":[[{"params":["message"],"type":"field"}]],"tags":[{"key":"tname","operator":"=","value":"myth"},{"condition":"AND","key":"vdc_name","operator":"=","value":"hamdy"},{"condition":"AND","key":"explorer","operator":"=","value":"dev"}]}]
```
![image](https://user-images.githubusercontent.com/526328/105984628-1567ec00-60a3-11eb-850b-0310d80d1ea3.png)

**Comment by waleedhammam** [comment]
fixed in https://github.com/threefoldtech/js-sdk/issues/2372

should do update after that 
![Screenshot from 2021-01-27 14-46-58](https://user-images.githubusercontent.com/10658229/105993354-fa9b7480-60ae-11eb-8ff6-47887dd0f304.png)
