### ISSUE TITLE
Add Presearch Solution

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/vdc-solutions-charts#78]
- [x] Get all requirements from Presearch
- [x] Prepare images
- [x] Prepare helm charts
- [x] Prepare chatflows
- [x] Prepare node status page
- [x] Test and Roll out

**Comment by hossnys** [comment]
verified 

![Screenshot from 2021-02-24 11-29-48](https://user-images.githubusercontent.com/26298009/108984203-54845f80-7698-11eb-94e5-448b4116297b.png)

![Screenshot from 2021-02-24 11-30-12](https://user-images.githubusercontent.com/26298009/108984207-55b58c80-7698-11eb-9d21-c0575e62f711.png)

![Screenshot from 2021-02-24 11-46-13](https://user-images.githubusercontent.com/26298009/108984211-56e6b980-7698-11eb-8cf1-f2bb9200d259.png)
