### ISSUE TITLE
Add Dash full node Solution

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/vdc-solutions-charts#82]
- [x] Get all requirements from Dash
- [x]  Prepare images
- [x]  Prepare helm charts
- [x]  Prepare chatflows
- [x]  Prepare node status page
- [x]  Test and Roll out

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch 
`development`

![image](https://user-images.githubusercontent.com/46320202/120645157-6421fa00-c478-11eb-8294-9c9e74720674.png)
