### ISSUE TITLE
tomochain ports

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc-solutions-charts#9]
similar to #8 #7 #6 

![image](https://user-images.githubusercontent.com/64129/102283366-fb32de00-3f3a-11eb-8885-3309366a426e.png)
https://docs.tomochain.com/masternode-and-dex/masternode/run-a-full-node/docker#ports

https://github.com/threefoldfoundation/blockchain_partners/blob/master/Tomochain/helm/templates/service.yaml seems to cover only ssh

**Comment by abdulgig** [comment]
Relevant ports exposed and helm charts updated
